<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <WarnOnPackingNonPackableProject>false</WarnOnPackingNonPackableProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Linkernizer.DependencyInjection\Linkernizer.DependencyInjection.csproj" />
    <ProjectReference Include="..\Linkernizer\Linkernizer.csproj" />
  </ItemGroup>

</Project>
