<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <PackageId>Linkernizer.DependencyInjection</PackageId>
    <Title>Linkernizer.DependencyInjection</Title>
    <Description>Dependency injection extensions for Linkernizer.</Description>
    <PackageTags>autolink;linkify;linkification;links;url;email;hyperlink;anchor;html;markup;dependencyinjection;di</PackageTags>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <Version>1.0.0</Version>
    <IsAotCompatible>true</IsAotCompatible>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.301" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Linkernizer\Linkernizer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="..\images\icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
